In [19]:
import torch
from torch import nn

In [3]:
scaler = torch.tensor(7)

In [7]:
scaler, scaler.ndim, scaler.item()  # item works only with a scaler tensor

(tensor(7), 0, 7)

In [8]:
vector = torch.tensor([7, 7])

In [9]:
vector.ndim, vector.shape

(1, torch.Size([2]))

In [10]:
random_tensor = torch.rand(size=(1, 3))

In [11]:
random_tensor

tensor([[0.0244, 0.1978, 0.7303]])

In [12]:
r1, r2 = torch.rand(size=(1, 3), dtype=torch.float32), torch.rand(size=(1, 3), dtype=torch.float64)

In [13]:
r = r1 + r2

In [15]:
r1, r2, r

(tensor([[0.7844, 0.8609, 0.3162]]),
 tensor([[0.5545, 0.0894, 0.3624]], dtype=torch.float64),
 tensor([[1.3389, 0.9503, 0.6786]], dtype=torch.float64))

In [14]:
r.dtype

torch.float64

In [16]:
r1.shape, r2.shape

(torch.Size([1, 3]), torch.Size([1, 3]))

In [ ]:
r @ r2.T  # matrix multiplication requires both to have same data types

tensor([[1.0733]], dtype=torch.float64)

In [20]:
torch.manual_seed(42)
linear = nn.Linear(in_features=2, out_features=6)

In [31]:
tensor_A = torch.tensor([
    [1, 2],
    [3, 4],
    [5, 6],
    [3, 5]
], dtype=torch.float32)
x = tensor_A
output = linear(x)

In [32]:
x, linear.weight, output

(tensor([[1., 2.],
         [3., 4.],
         [5., 6.],
         [3., 5.]]),
 Parameter containing:
 tensor([[ 0.5406,  0.5869],
         [-0.1657,  0.6496],
         [-0.1549,  0.1427],
         [-0.3443,  0.4153],
         [ 0.6233, -0.5188],
         [ 0.6146,  0.1323]], requires_grad=True),
 tensor([[ 2.2368,  1.2292,  0.4714,  0.3864,  0.1309,  0.9838],
         [ 4.4919,  2.1970,  0.4469,  0.5285,  0.3401,  2.4777],
         [ 6.7469,  3.1648,  0.4224,  0.6705,  0.5493,  3.9716],
         [ 5.0788,  2.8466,  0.5896,  0.9437, -0.1786,  2.6101]],
        grad_fn=<AddmmBackward0>))

In [33]:
x.shape, linear.weight.shape, output.shape

(torch.Size([4, 2]), torch.Size([6, 2]), torch.Size([4, 6]))

In [36]:
x.max(), x.min(), x.type(torch.float32).mean(), x.sum(), x.argmax(), x.argmin()

(tensor(6.), tensor(1.), tensor(3.6250), tensor(29.), tensor(5), tensor(0))

In [37]:
x.shape

torch.Size([4, 2])

In [40]:
z = x.reshape(1,  1, 8)
z

tensor([[[1., 2., 3., 4., 5., 6., 3., 5.]]])

In [42]:
z.view(8)

tensor([1., 2., 3., 4., 5., 6., 3., 5.])

In [43]:
x

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [3., 5.]])

In [44]:
x.shape

torch.Size([4, 2])

In [45]:
a = torch.rand_like(x)

In [49]:
x.ndim

2

In [50]:
b = torch.stack([x, a], dim=0)
c = torch.stack([x, a], dim=1)
b.shape, c.shape

(torch.Size([2, 4, 2]), torch.Size([4, 2, 2]))

In [54]:
x.shape, a.shape, b.shape, c.shape

(torch.Size([4, 2]),
 torch.Size([4, 2]),
 torch.Size([2, 4, 2]),
 torch.Size([4, 2, 2]))

In [58]:
x

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [3., 5.]])

In [53]:
x, a, b,c

(tensor([[1., 2.],
         [3., 4.],
         [5., 6.],
         [3., 5.]]),
 tensor([[0.2666, 0.6274],
         [0.2696, 0.4414],
         [0.2969, 0.8317],
         [0.1053, 0.2695]]),
 tensor([[[1.0000, 2.0000],
          [3.0000, 4.0000],
          [5.0000, 6.0000],
          [3.0000, 5.0000]],
 
         [[0.2666, 0.6274],
          [0.2696, 0.4414],
          [0.2969, 0.8317],
          [0.1053, 0.2695]]]),
 tensor([[[1.0000, 2.0000],
          [0.2666, 0.6274]],
 
         [[3.0000, 4.0000],
          [0.2696, 0.4414]],
 
         [[5.0000, 6.0000],
          [0.2969, 0.8317]],
 
         [[3.0000, 5.0000],
          [0.1053, 0.2695]]]))

In [61]:
z.shape

torch.Size([1, 1, 8])

In [63]:
z.squeeze().shape

torch.Size([8])

In [68]:
torch.manual_seed(0)

In [69]:
q1 = torch.rand(size=(7, 7))

In [70]:
s = torch.rand(size=(1, 7))

In [71]:
q1.shape, s.shape

(torch.Size([7, 7]), torch.Size([1, 7]))

In [73]:
l = s @ q1

In [74]:
l.max(), l.min(), l.argmax(), l.argmin()

(tensor(2.8454), tensor(1.4257), tensor(2), tensor(6))

In [76]:
torch.manual_seed(7)
d = torch.rand(size=(1, 1, 10))
k = d.squeeze()
d, d.shape, k, k.shape

(tensor([[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]),
 torch.Size([1, 1, 10]),
 tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]),
 torch.Size([10]))